{% set name = "reademption" %}
{% set version = "2.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/f4/59/07ef707b9b3bf9e7d392b7c09508f37037990fa9ae22b473149269ff11d3/READemption-2.0.4.tar.gz"
  sha256: e6ceb39a01b289e89b6d7cebd79ffb5b09679fd9255c621fc6e33450afb96345

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - biopython >=1.79
    - matplotlib >=3.5.2
    - pandas >=1.4.3
    - pip
    - pysam >=0.19.1
    - python
    - seaborn >=0.11.2
    - sphinx-argparse >=0.2.5
  run:
    - biopython >=1.79
    - matplotlib >=3.5.2
    - pandas >=1.4.3
    - pysam >=0.19.1
    - python
    - seaborn >=0.11.2
    - sphinx-argparse >=0.2.5

test:
  imports:
    - reademptionlib
    - tests

about:
  home: The package home page
  license: MIT
  license_family: MIT
  license_file: 
  summary: "A RNA-Seq Analysis Pipeline"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
