language: python
python:
  - "3.7"
# command to install dependencies
install:
  - "pip install matplotlib"
  - "pip install biopython"
  - "pip install pysam"
  - "pip install pandas"
  - "conda install -c bioconda segemehl"
# command to run tests
script: pytest
