language: python
python:
  - "3.7"
# command to install dependencies
install:
  - "pip install matplotlib"
  - "pip install biopython"
  - "pip install pysam"
  - "pip install pandas"
  - "wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh"
  - "chmod +x miniconda.sh"
  - "./miniconda.sh -b"
  - "export PATH=/home/travis/miniconda/bin:$PATH"
  - "conda update --yes conda"
  - "conda install -c bioconda segemehl"
# command to run tests
script: pytest
