language: python
python:
  - "3.6"
# command to install dependencies
install:
  - "pip install matplotlib"
  - "pip install biopython"
  - "pip install pysam"
# command to run tests
script: pytest tests/test_fasta.py
